import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import localFont from "next/font/local";

const gtWalsheim = localFont({
  src: [
    {
      path: "../fonts/GTWalsheimProRegular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/GTWalsheimProBold.woff2",
      weight: "700",
      style: "bold",
    },
    {
      path: "../fonts/GTWalsheimProMedium.woff2",
      weight: "500",
      style: "medium",
    },
  ],
});

export const metadata: Metadata = {
  title: "Dimension Technical Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={gtWalsheim.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
